### ISSUE TITLE
Improve new API naming

### ISSUE THREAD

**Issue by d4vidi** [wix/redux-testkit#4]
- `Reducer` feels like a weird starting point for the BDD-ish 'test chain'.
- `expect` isn't a very descriptive name as to the fact that it receives a redux action  and de-facto mutates the state.

An example of something I might consider friendlier:

```js
TestKit.forReducer(reducer).withAction(action).expectStateToEqual(state)
// OR
TestKit.withReducer(reducer).givenAction(action).expectStateToEqual(state)
// OR
TestKit.withReducer(reducer).givenAction(action).expectState.toEqual(state)
```
etc.

@ethanshar @talkol wdyt?

**Comment by DanielZlotin** [comment]
I vote for `TestKit.forReducer(reducer).withAction(action).expectStateToEqual(state)`

**Comment by ethanshar** [comment]
ok I wrote some examples just to get a consistent structure.
I came up with the followings:
for Reducer (need to pick the right naming, but the structure is the same):
```Reducer(uut).withState(state).expect(action).toReturnState();
Reducer(uut).withState(state).execute(action);
Reducer(uut).withAction(action).onState(state).toReturnState()
Reducer(uut).givenAction(action).onState(state).toReturnState()
```
* this one has a lot of options as I can see it, so Im not sure what’s the best one.

for Selectors:
```Selector(uut).onState(state).withArgs(...args).toReturn();
Selector.expect(uut).onState(state).withArgs(...args).toReturn();
Selector.expect(uut).onState(state).withArgs(…args).execute();
```

Thunk is more limited, so to make it make consistent with the other I thought about this:
```Thunk(uut).withState(state).withArgs(…args).execute();```

Now the way I see it, it’s kind of a builder pattern, so the order of the commands (withState, withArgs..) doesn’t really matters except for the executing commands like (execute, toReturn, toReturnState)
I believe this is way more readable, each command responsible for specific part of the chain (no more sending bunch of arguments in one command which I despise), and some commands are of course optional (e.g withState).

Eventually the executing command have to make sure it has the required parts (action, selector, state and so on..) and in case it doesn't, it should throw and error or something, otherwise return the expected result.

What do you think ?

**Comment by talkol** [comment]
I propose:

`Reducer(reducer).withState(state).expect(action).toReturnState(result)`
`Reducer(reducer).withState(state).execute(action)`

`Selector(selector).withState(state).expect(...args).toReturn(result)`
`Selector(selector).withState(state).execute(...args)`

`Thunk(thunk).withState(state).execute(...args)`

In all of them, if you don't call `.withState()` it will use the default

**Comment by ethanshar** [comment]
ok, looks good! the syntax is pretty consistent and readable and that's what important.

**Comment by talkol** [comment]
I'll close with the fixing commit actually :)

**Comment by ethanshar** [comment]
fixed
